# Generated by Django 3.0.7 on 2020-06-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Uncategorized'), (2, 'Beauty and Personal Care'), (3, 'Wooden Utensils'), (4, 'Stationary'), (5, 'Clay Pots')], default=3)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
            ],
        ),
    ]
